### PR TITLE
fixed DQAstats logic for ship-dataset

### PR DESCRIPTION
**Pull request by kapsner**
Hi @JoanyMarino, I have repaired the code for DQAstats. Please check reproducibility. Best, Lorenz

### CODE REVIEW

**Comment by JoanyMarino** [comment]
Thanks, @kapsner! I was not able to generate the PDF report (although the Rmd is produced and stored in the temp directory). This is the error I get when I try to execute `dqa`:

```
Version of 'DIZutils': 0.0.11
Version of 'DQAstats': 0.2.2
[Info] using future::plan("multisession") (d142855e3c)
Error in makeNode(workers[[ii]], port = port, ..., rank = ii, action = "options",  : 
  could not find function "makeNode"
In addition: Warning message:
In dir.create(file.path(logfile_dir)) :
  'C:\Users\marinoj\AppData\Local\Temp\RtmpCESzsM' already exists
```

I could not find any documentation on this `makeNode `function, any ideas?

**Comment by kapsner** [comment]
Hi @JoanyMarino, many thanks for that information. This is realted to the initialization of the parallel backend on windows I assume. Please check if this is solved by #2

**Comment by JoanyMarino** [comment]
Works nicely, thanks @kapsner!

**Comment by kapsner** [comment]
> 

👍 perfect. Sorry for that inconvenience. I have just updated our repo to have the argument `parallel=FALSE` by default in the next CRAN release: https://github.com/miracum/dqa-dqastats/commit/d11943b5c95709c12ff1ad7cfa833f6c7dc4ae1d#diff-cce596c7ed3bce8d80c16b82b3c4c62759de5f7a53f191dccb8f0754f5c42047R107

**Pull request merged**
